name: Generate ASCII Artwork 
on: push 

jobs: 
    build_job_1:
       runs-on: ubuntu-latest

    build_job_2:
       steps:
       - name: Checkout Repo
         uses: actions/checkout@v4

    build_job_3:
       - name: list Repo Files 
         run: pwd 
              ls -ltra  

       - name: Executing Shell script
         run: |
           chmod +x .github/ascii-scipt.sh
           ./.github/ascii-scipt.sh
        