name: Generate ASCII Artwork 
on: push 

jobs: 
    build_job_1:
       runs-on: ubuntu-latest
       steps:
       - name: Install Cowsay 
         run: sudo apt-get install cowsay -y

       
       - name: Execute Cowsay CMD 
         run: cowsay -f dragon "Run for cover..." >> dragon.txt 
         run: ls -ltra  
         

       - uses: actions/upload-artifact@v4
         with:
           name: dragon.txt 
           path: /home/runner/work/Project-B/Project-B/


       - name: Sleep for 30 secs
         run: sleep 30
        
    test_job_2:
       needs: build_job_1
       runs-on: ubuntu-latest 
       steps:
       - name: sleep for 10 seconds 
         run: sleep 10 

       - uses: actions/download-artifact@v5
         with:
           name: dragon.txt 
           path: /home/runner/work/Project-B/Project-B


       - name: Test File Exists
         run: grep -i "dragon" dragon.txt 

    deploy_job_3:
       runs-on: ubuntu-latest 
       steps:
       - name: Read file
         run: cat dragon.txt

       - name: Deploy 
         run: echo Deploying...   
